### PR TITLE
Adding vaadin-split-layout element to the collection

### LINKED ISSUE #65: Add split-layout component to the collection

### PR DESCRIPTION
**Pull request by manolo**
Fixes #65

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core-elements/66)

### CODE REVIEW

**Comment by jouni** [comment]
Hmm, now that I think about this, perhaps we can’t have this in master. Once grid 1.2 comes out, we should update the version to 1.2 for the bundle as well, and it should not contain the split-layout.

So how, do we do this? A separate branch?

**Comment by manolo** [comment]
I think master should have grid 1.2 and split layout. But we create a separate branch for releasing 1.1.3 removing the split  . Sounds ok ? 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66#-:-KPw61iitEfYZQq24v3b:b-9tn2l9)*

**Comment by jouni** [comment]
Yeah, that sounds ok :thumbsup: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66#-:-KPwEdueuguOOFyjtfW-:bp4l1z7)*

**Comment by tehapo** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 32 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66#-KQKBkH16CV4iFZ0fmFI:-KQKBkH2Q5GL5fseUH3i:b-nw2s79) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/04eef96f426608db0a04f5a468c6e6946935568a/bower.json#L32)):*
> ```JSON
>     "vaadin-date-picker": "vaadin/vaadin-date-picker#~1.1.0",
>     "vaadin-upload": "vaadin/vaadin-upload#~1.0.0",
>     "vaadin-split-layout": "vaadin/vaadin-split-layout#~0"
> ```

I guess this should now be updated to `vaadin-split-layout#~0.1.0` as the first version is released?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 32 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66#-KQKBkH16CV4iFZ0fmFI:-KQPb1ohIzgQJ7tfqD3j:b-ctmubv) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/04eef96f426608db0a04f5a468c6e6946935568a/bower.json#L32)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> I guess this should now be updated to `vaadin-split-layout#~0.1.0` as the first version is released?
</details>
It depends if we want to pick up 0.2.0 when it's released. I understood that we use 0.x to mark that it not stable enough version until 1.x.
So ~0 means 0.1 0.2 ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bower.json, line 42 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66#-KQUv49YxZlyHsBwEBGt:-KQUv49ZIoCHNAd1y1Dw:bofdiyr) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/04eef96f426608db0a04f5a468c6e6946935568a/bower.json#L42)):*
> ```JSON
>     "components-demo-resources": "vaadin/components-demo-resources#master",
>     "mock-http-request": "philikon/MockHttpRequest#master",
>     "iron-demo-helpers": "PolymerElements/iron-demo-helpers#^1.0.0",
> ```

@tehapo these two lines are necessary to correctly display demos in cdn

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bower.json, line 42 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66#-KQUv49YxZlyHsBwEBGt:-KQUzfnOwF6bxVSL5Zlp:bcr5s2o) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/04eef96f426608db0a04f5a468c6e6946935568a/bower.json#L42)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> @tehapo these two lines are necessary to correctly display demos in cdn
</details>
Got it, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66)*

**Comment by tehapo** [comment]
I picked up the changes currently needed into `master` branch. I think we should now abandon this PR as the `master` versions are separately deployed into cdn.

Let's add the `vaadin-split-layout` dependency when we are ready to include it in the release version of the bundle.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/66#-:-KQV7J763PaS8-itbmol:b-jxcacv)*

**Pull request closed without merging**
