### PR TITLE
Convert to asciidoc

### PR DESCRIPTION
**Pull request by jouni**
Rename “doc” folder to “docs” to align with individual elements. Remove
redundant “index.asciidoc” file.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core-elements/42)

### CODE REVIEW

**Comment by jounik** [comment]
@magi42, review if needed.

**Comment by tomivirkki** [comment]
Should also change the docsite build task to use the correct folder https://github.com/vaadin/vaadin-core-elements/blob/master/tasks/docsite.js#L44

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-:-KFNzyfTzELj2QeTLQkc:531316774)*

**Comment by jouni** [comment]
@tomivirkki: thanks, fixed!

**Comment by tomivirkki** [comment]
:lgtm: 

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-:-KFcIa96dK1comixGxDQ:980077423)*

**Comment by magi42** [comment]
OK I'll make comments. I don't think these have been language-checked before, so I'll do that as well.

**Comment by jouni** [comment]
Thanks! Yeah, I’m pretty sure these haven’t been language checked.

**Comment by magi42** [comment]
Review status: all files reviewed at latest revision, 29 unresolved discussions, all commit checks successful.

---

*[docs/elements-getting-started.adoc, line 9 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcY0rctKk_bFU1M0HK:-KFcY0rctKk_bFU1M0HL:1909282271) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L9)):*
* Missing article: "_the_ Vaadin Code Elements bundle" (the article is for "the ... bundle")

---

*[docs/elements-getting-started.adoc, line 13 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcYGRyhso9XWHzc2Tb:-KFcYGRyhso9XWHzc2Tc:1667040179) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L13)):*
* Use serial comma in lists of three or more: A, B, and C.
* Maybe adding "that" here would clarify: "the URL _that_ you"
* Remove "will", it's not relevant to use future tense here.

---

*[docs/elements-getting-started.adoc, line 15 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcYllsd0l8MESvDiZ_:-KFcYlltVMa0JSS8IyNa:-109624862) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L15)):*
Use title case for all section titles: "Create a New Folder". There's some variations of title case, we use something like [this](http://grammar-monster.com/lessons/capital_letters_title_case.htm).

---

*[docs/elements-getting-started.adoc, line 17 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcZk0Zz8UoZhHbRGFW:-KFcZk0Zz8UoZhHbRGFX:-849903738) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L17)):*
* more simply "...and change to the folder:" (note the colon)

---

*[docs/elements-getting-started.adoc, line 22 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFccNmywuTRbseGBIBZ:-KFccNmz9iBefItUu9KP:-181431525) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L22)):*
Please use emphasis for CLI examples. It would probably go like this:
```
[subs="normal"]
----
[prompt]#$# [command]#mkdir# [replaceable]#my-project#
[prompt]#$# [command]#cd# [replaceable]#my-project#
----
```
(In these it would be *very* important to use site preview and not just Atom preview, as such formatting is very easily broken.)

---

*[docs/elements-getting-started.adoc, line 28 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFc_3y3e7aNU6CBv1Mr:-KFc_3y3e7aNU6CBv1Ms:1652685130) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L28)):*
* Article: "_The_ recommended way"
* Use to-infinitive rather than gerund: "...dependencies is _to use_" (to-infinitive was used earlier in the sentence)

---

*[docs/elements-getting-started.adoc, line 35 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFca7M5Vu5nGlDOJQgw:-KFca7M5Vu5nGlDOJQgx:-278097529) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L35)):*
* Article: "_the_ Vaadin Core Elements bundle"
* Use `[filename]#bower_components#` style also for folder names.
* "inside your project's folder" -> "under your project folder"

---

*[docs/elements-getting-started.adoc, line 37 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcaZgBSs6gbPSFCyEe:-KFcaZgBSs6gbPSFCyEf:-1876235252) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L37)):*
* rather have: "install and update"

---

*[docs/elements-getting-started.adoc, line 45 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcd2buFRiPaZ-eaGj1:-KFcd2buFRiPaZ-eaGj2:-2051285172) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L45)):*
* I don't understand where the "see example below" refers to. Maybe just leave it out.
* Is CDN an understandable concept? I had never heard about CDN before just a few months ago and it was a bit confusing to me at first what it meant. Maybe explain it a bit. Also, we should probably refer to "Vaadin CDN" and not just any CDN, as we're using `cdn.vaadin.com` here.

---

*[docs/elements-getting-started.adoc, line 47 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcb27iEsjyw14-7SqU:-KFcb27jFzykxy21_rfS:1219732109) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L47)):*
* Not sure if we should consider "vaadin-grid" a product name or element name here. If latter, use `[vaadinelement]#vaadin-grid#`.
* It says "use" here, but reading this I have no clue how to "use" it at this point. I assume that it is used by <link>ing it in a HTML header, as described later, but it is rather confusing at this point. Maybe you should give the usage HTML for each of the installation methods, at least briefly.

---

*[docs/elements-getting-started.adoc, line 51 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFce9CiHbWgEZctrq4j:-KFce9Cjx9kXCEyLSAzA:109898189) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L51)):*
So maybe have a proper HTML head example here.

---

*[docs/elements-getting-started.adoc, line 65 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFceEqQ4W51cH7S6sCL:-KFceEqQ4W51cH7S6sCM:-1155284993) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L65)):*
The title seems to miss an article and something else. Maybe: "Download as a ZIP"

---

*[docs/elements-getting-started.adoc, line 68 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcf6jagSFDz_Nbbf6f:-KFcf6jbSj4Or6pG43s2:-1694266) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L68)):*
* Use `[filename]#deps#` style also for folder names.
* Maybe rather: "...`for example, in a [filename]#deps# folder`"

---

*[docs/elements-getting-started.adoc, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcfTxn33ER2xgwuCvl:-KFcfTxn33ER2xgwuCvm:-2000102592) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L72)):*
* Use `[filename]#index.html#`
* Where's the following code? If you say "following", it should follow immediately.

---

*[docs/elements-getting-started.adoc, line 76 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcfrxnE6gGr4sHBqFB:-KFcfrxnE6gGr4sHBqFC:-1346236395) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L76)):*
* Use `[elementname]#!doctype html#` for emphasis (leave out `<..>` as they come from the style.

---

*[docs/elements-getting-started.adoc, line 77 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcg9oFhLUsGUxDDab8:-KFcg9oFhLUsGUxDDab9:819225336) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L77)):*
Use `[filename]` style for the file names.

---

*[docs/elements-getting-started.adoc, line 78 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcgVPeaBqJw3eYbMHK:-KFcgVPeaBqJw3eYbMHL:-944069788) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L78)):*
* WebComponentsReady sounds like a class or object name, so use `[classname]#WebComponentsReady#`.

---

*[docs/elements-getting-started.adoc, line 147 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFch_MXyf-drlX0FUGU:-KFch_MXyf-drlX0FUGV:2091873715) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L147)):*
* "notice, that" -> "notice that"
* "the port 3000" -> "the port number" or "the port number may be different in the server you use"

---

*[docs/elements-introduction.adoc, line 11 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFciAC4nLbnQHj_sGss:-KFciAC4nLbnQHj_sGst:1484977958) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L11)):*
* Serial comma in lists of three or more:  "Iron, Paper, and other"

---

*[docs/elements-introduction.adoc, line 13 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcie4Vk1GF5FLKhXgk:-KFcie4Vk1GF5FLKhXgl:-2028627142) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L13)):*
* "which" -> "that" (it's a restrictive clause)
* "See the "Integrations" section" – use a proper reference: `<<dummy/../../../

---

*[docs/elements-introduction.adoc, line 15 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnn039tjSX3upn62Jc:-KFnn039tjSX3upn62Jd:-274732118) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L15)):*
Period mission from the end.

---

*[docs/elements-introduction.adoc, line 24 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnnE8yvGPSl6qaqi3v:-KFnnE8yvGPSl6qaqi3w:-783603927) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L24)):*
* Period missing from the end.
* The » character may look a bit odd. It's maybe a sort of styling thing, which should be handled in the link style. It could also cause trouble in processing the documentation, as it's a non-ASCII character.

---

*[docs/elements-introduction.adoc, line 30 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnnijvI0_l92fKe3g-:-KFnnijwNJlhoElgytt6:-2012968309) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L30)):*
* You could use the `[elementname]#video#` tag here rather than code style. Also for the input element.
* Use (serial) comma before "and so on".

---

*[docs/elements-introduction.adoc, line 35 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnoHW9obfqqPFbuINV:-KFnoHWAF7B2Z0gz5nDI:955778373) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L35)):*
* You could rather have these items as a named list instead of bullet-points:
```
*Template element*::
"The HTML template element..."
```
And so forth for all the four items.
* ” is a non-ASCII character, please avoid.
* Use [elementname]#template#.
* Rather long and complex sentence.

---

*[docs/elements-introduction.adoc, line 38 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnqNV-fKs_q4jTF_B1:-KFnqNV0_OLpZaX1DEUQ:-1333690419) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L38)):*
* Maybe rather: "_Shadow DOM allows keeping them separate_..."

---

*[docs/elements-introduction.adoc, line 49 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnt6sFlFt1gUSs3sOT:-KFnt6sGvAbN7KXVe_6S:-1548407220) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L49)):*
There's again the non-ASCII » character that could cause trouble sometime. This line kind of fits here as is, although looks a bit odd without a period or the odd character.

---

*[docs/elements-introduction.adoc, line 55 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFntmeeAraBrdMg6DRb:-KFntmefyieolIAgJhJI:896325547) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L55)):*
* Maybe remove "it" in "it adds"
* Use serial comma in: "_binding, and_"

---

*[docs/elements-introduction.adoc, line 61 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnu6Ar8bLW4o613kai:-KFnu6Ar8bLW4o613kaj:-1897881290) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L61)):*
Hmm hmm, again more of these. They sort of fit here as is. Hmm.

---

*[docs/elements-introduction.adoc, line 74 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnu_RPUt7xAw95tA1u:-KFnu_RQPCTy5LhATCaR:1463504923) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L74)):*
Use colon (:) after a sentence introducing a list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 29 unresolved discussions.

---

*[docs/elements-getting-started.adoc, line 9 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcY0rctKk_bFU1M0HK:-KGEFeRIQrJTB6fDa1aJ:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L9)):*
done

---

*[docs/elements-getting-started.adoc, line 13 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcYGRyhso9XWHzc2Tb:-KGEFvrOBGpC2gXUw3xn:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L13)):*
done

---

*[docs/elements-getting-started.adoc, line 15 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcYllsd0l8MESvDiZ_:-KGEG03IxD3Fcpv-otm_:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L15)):*
done

---

*[docs/elements-getting-started.adoc, line 17 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcZk0Zz8UoZhHbRGFW:-KGEGCO8BSUnEY_hIdUF:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L17)):*
done

---

*[docs/elements-getting-started.adoc, line 22 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFccNmywuTRbseGBIBZ:-KGEGLCllhvid6QwWRVK:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L22)):*
done

---

*[docs/elements-getting-started.adoc, line 28 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFc_3y3e7aNU6CBv1Mr:-KGEGiU7e5lbEOGHiG3w:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L28)):*
done

---

*[docs/elements-getting-started.adoc, line 35 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFca7M5Vu5nGlDOJQgw:-KGENQgdiTXNaMB-Olbi:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L35)):*
done

---

*[docs/elements-getting-started.adoc, line 37 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcaZgBSs6gbPSFCyEe:-KGENRkQ6wEjTM0YsfPk:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L37)):*
done

---

*[docs/elements-getting-started.adoc, line 45 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcd2buFRiPaZ-eaGj1:-KGEIfUSYNepW2VCfKdN:-844765349) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L45)):*
added link, so as people not familiar with the term can read about it.

---

*[docs/elements-getting-started.adoc, line 47 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcb27iEsjyw14-7SqU:-KGENYGo-FmfxN0uz1Qn:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L47)):*
done

---

*[docs/elements-getting-started.adoc, line 51 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFce9CiHbWgEZctrq4j:-KGEJK9ev3m5aSGVzsT3:-969640640) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L51)):*
changed link by html import tag

---

*[docs/elements-getting-started.adoc, line 65 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFceEqQ4W51cH7S6sCL:-KGEJRdlKcMCcnMX43e3:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L65)):*
done

---

*[docs/elements-getting-started.adoc, line 68 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcf6jagSFDz_Nbbf6f:-KGEN_YZfmxv6NXjoXTL:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L68)):*
done

---

*[docs/elements-getting-started.adoc, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcfTxn33ER2xgwuCvl:-KGEJqNK6prAgoHjTdux:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L72)):*
done

---

*[docs/elements-getting-started.adoc, line 76 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcfrxnE6gGr4sHBqFB:-KGEK6bg9NF5SppvNsL-:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L76)):*
done

---

*[docs/elements-getting-started.adoc, line 77 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcg9oFhLUsGUxDDab8:-KGEKI-i4KBjfaxchoX1:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L77)):*
done

---

*[docs/elements-getting-started.adoc, line 78 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFcgVPeaBqJw3eYbMHK:-KGEKN1w3mfU5fgJgutu:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L78)):*
done

---

*[docs/elements-getting-started.adoc, line 147 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFch_MXyf-drlX0FUGU:-KGEKZ4m1jqWvDLmRqAc:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-getting-started.adoc#L147)):*
done

---

*[docs/elements-introduction.adoc, line 11 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFciAC4nLbnQHj_sGss:-KGEKrJt_s04FzMBVKhH:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L11)):*
done

---

*[docs/elements-introduction.adoc, line 15 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnn039tjSX3upn62Jc:-KGELAt3Mrt1DWBm4oG6:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L15)):*
done

---

*[docs/elements-introduction.adoc, line 24 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnnE8yvGPSl6qaqi3v:-KGENj2X6eM0D77jL_Wy:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L24)):*
done

---

*[docs/elements-introduction.adoc, line 30 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnnijvI0_l92fKe3g-:-KGELV_X31M4e_-GTANv:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L30)):*
done

---

*[docs/elements-introduction.adoc, line 35 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnoHW9obfqqPFbuINV:-KGEMcCUO8j3dX4e6tvE:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L35)):*
done

---

*[docs/elements-introduction.adoc, line 38 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnqNV-fKs_q4jTF_B1:-KGEMcyuj7lxIgbV1YLZ:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L38)):*
done

---

*[docs/elements-introduction.adoc, line 49 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnt6sFlFt1gUSs3sOT:-KGEMi3YiN7RxCjXfhAu:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L49)):*
done

---

*[docs/elements-introduction.adoc, line 55 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFntmeeAraBrdMg6DRb:-KGEMv8kjZfgEy4DKwaT:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L55)):*
done

---

*[docs/elements-introduction.adoc, line 61 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnu6Ar8bLW4o613kai:-KGEMz2G_oUcJt7s3sjY:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L61)):*
done

---

*[docs/elements-introduction.adoc, line 74 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42#-KFnu_RPUt7xAw95tA1u:-KGEN3sht58hjEsHCCbf:677588487) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e174b21cb40d80aeb578ad326a0457b5b380f76e/docs/elements-introduction.adoc#L74)):*
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/42)*

**Pull request merged**
