### PR TITLE
Add vue.js docs

### LINKED ISSUE #76: Vue.js integration example
We should add an example how to integrate with Vue.js

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #76

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core-elements/79)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/integrations/integrations-vuejs.adoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyXQg49NrudsSMMTIm:-KVyXQg49NrudsSMMTIn:bv5vtzf) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L10)):*
> ```AsciiDoc
> 
> link:https://vuejs.org/[Vue.js] is a library for building interactive web interfaces with JavaScript.
> Vue's components can be loosely compared to Vaadin Elements and both provide a very similar development style.
> ```

I don't understand this, why are there so closed? look-an-feel? internals?

---

*[docs/integrations/integrations-vuejs.adoc, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyXo2SpBn9cuniTjoY:-KVyXo2SpBn9cuniTjoZ:b-nsutlq) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L44)):*
> ```AsciiDoc
> ----
> 
> . You need to add the Web Components polyfill to the [elementname]#head# section of your [filename]#index.html#.
> ```

I would mention that chrome does not need the polyfill. Something like if your application is going to be used with browsers that does not yet implement the full WC spec ...

---

*[docs/integrations/integrations-vuejs.adoc, line 45 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyY2homL7hNGGuKfbd:-KVyY2hpv7yqhT3rTxOq:b-ckbqii) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L45)):*
> ```AsciiDoc
> 
> . You need to add the Web Components polyfill to the [elementname]#head# section of your [filename]#index.html#.
> This will allow the use of Vaadin Elements in all modern browsers.
> ```

what are modern browsers here ?

---

*[docs/integrations/integrations-vuejs.adoc, line 60 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyYLRq7QBHIgaOXATy:-KVyYLRq7QBHIgaOXATz:b-12iw0f) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L60)):*
> ```AsciiDoc
> <template>
>   <div class="date-select">
>     <link rel="import" href="static/bower_components/vaadin-date-picker/vaadin-date-picker.html">
> ```

Is it necessary that each time you attach/detach a new component to the ui, we make the import call. I know the import spec should skip this if already done, but it's ugly to see this in the dom. And also it could happen that you add multiple components at the same time and all are going to do the import.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79)*

**Comment by samiheikki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/integrations/integrations-vuejs.adoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyXQg49NrudsSMMTIm:-KVyebnBJgCKZLloms70:bqhwwk3) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L10)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I don't understand this, why are there so closed? look-an-feel? internals?
</details>
https://vuejs.org/v2/guide/comparison.html#Polymer

---

*[docs/integrations/integrations-vuejs.adoc, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyXo2SpBn9cuniTjoY:-KVyfzC9nkYp8zFkAw_X:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L44)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I would mention that chrome does not need the polyfill. Something like if your application is going to be used with browsers that does not yet implement the full WC spec ...
</details>
Done.

---

*[docs/integrations/integrations-vuejs.adoc, line 45 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyY2homL7hNGGuKfbd:-KVygId7YSdXsDdrbtiv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L45)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> what are modern browsers here ?
</details>
Done.

---

*[docs/integrations/integrations-vuejs.adoc, line 60 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyYLRq7QBHIgaOXATy:-KVyh1E1-bSbeBWCdM7K:b-2itl4l) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L60)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Is it necessary that each time you attach/detach a new component to the ui, we make the import call. I know the import spec should skip this if already done, but it's ugly to see this in the dom. And also it could happen that you add multiple components at the same time and all are going to do the import.
</details>
My point adding it to there was to do a lazy load of elements. So we would not load everything in the index.html, but load it in the component that we need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/integrations/integrations-vuejs.adoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyXQg49NrudsSMMTIm:-KVymJJELJnffMOUOmuE:b-walr6k) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L10)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> https://vuejs.org/v2/guide/comparison.html#Polymer
</details>
Interesting, could you link to that? [loosely compared] 

---

*[docs/integrations/integrations-vuejs.adoc, line 60 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyYLRq7QBHIgaOXATy:-KVymdnvNtZRIo7knKT_:b-as6drt) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L60)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> My point adding it to there was to do a lazy load of elements. So we would not load everything in the index.html, but load it in the component that we need it.
</details>
That is the point in gwt-polymer as well, but there is done by code, so there are no links in code when inspecting the dom.
I would include a note saying that having here the imports facilitates not to import the components in the hosting page. That it's not a performance hit, since import takes care of not importing already imported elements. And that those links will be present in the dom.

Also I think it could be some issues, for instance, only in chrome the import would be synchronous, but in polyfilled browsers is async, that means that if you set properties before the component is registered those properties are gone.

For instance this example might not work:

```
<template>
  <div class="date-select">
    <link rel="import" href="static/bower_components/vaadin-date-picker/vaadin-date-picker.html">
     <vaadin-date-picker label="Syntymäpäivä" id="finnish" value="1980-08-14">
     <script>
       var datepicker = document.querySelector('vaadin-date-picker#finnish');
       datepicker.i18n = {
           week: 'viikko',
           ... };
     </script>
   ...

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/integrations/integrations-vuejs.adoc, line 44 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyp8O7srsQH6H3AOIq:-KVyp8O8RcurNd6b9bvS:b-ur38y5) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/958804f07a9049436c2e9e52cdd41b9a15a96c31/docs/integrations/integrations-vuejs.adoc#L44)):*
> ```AsciiDoc
> ----
> 
> . For better broser support, you need to add the Web Components polyfill to the [elementname]#head# section of your [filename]#index.html#.
> ```

broser -> browser

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/integrations/integrations-vuejs.adoc, line 46 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVypG3w9BlUYiPDuT03:-KVypG3w9BlUYiPDuT04:bx03ml6) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/958804f07a9049436c2e9e52cdd41b9a15a96c31/docs/integrations/integrations-vuejs.adoc#L46)):*
> ```AsciiDoc
> . For better broser support, you need to add the Web Components polyfill to the [elementname]#head# section of your [filename]#index.html#.
> This will allow the use of Vaadin Elements in all evergreen browsers.
> Web Components are natively supported in Chrome and Opera and the polyfill is not required.
> ```

I would set a NOTE here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79)*

**Comment by samiheikki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/integrations/integrations-vuejs.adoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyXQg49NrudsSMMTIm:-KW1LccjC6-QnCWX4coc:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L10)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Interesting, could you link to that? [loosely compared] 
</details>
Done.

---

*[docs/integrations/integrations-vuejs.adoc, line 60 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyYLRq7QBHIgaOXATy:-KW1OJQjBXSRXWVviH-y:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/e3a56739bd39b25fbe10ea710f9907c09a6580f6/docs/integrations/integrations-vuejs.adoc#L60)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> That is the point in gwt-polymer as well, but there is done by code, so there are no links in code when inspecting the dom.
> I would include a note saying that having here the imports facilitates not to import the components in the hosting page. That it's not a performance hit, since import takes care of not importing already imported elements. And that those links will be present in the dom.
> 
> Also I think it could be some issues, for instance, only in chrome the import would be synchronous, but in polyfilled browsers is async, that means that if you set properties before the component is registered those properties are gone.
> 
> For instance this example might not work:
> 
> ```
> <template>
>   <div class="date-select">
>     <link rel="import" href="static/bower_components/vaadin-date-picker/vaadin-date-picker.html">
>      <vaadin-date-picker label="Syntymäpäivä" id="finnish" value="1980-08-14">
>      <script>
>        var datepicker = document.querySelector('vaadin-date-picker#finnish');
>        datepicker.i18n = {
>            week: 'viikko',
>            ... };
>      </script>
>    ...
> 
> ```
> 
</details>
Done.

---

*[docs/integrations/integrations-vuejs.adoc, line 44 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVyp8O7srsQH6H3AOIq:-KW1LLuuVIp--yfS6T6R:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/958804f07a9049436c2e9e52cdd41b9a15a96c31/docs/integrations/integrations-vuejs.adoc#L44)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> broser -> browser
</details>
Done.

---

*[docs/integrations/integrations-vuejs.adoc, line 46 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KVypG3w9BlUYiPDuT03:-KW1MUA4DRTEf6FgO2tf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/958804f07a9049436c2e9e52cdd41b9a15a96c31/docs/integrations/integrations-vuejs.adoc#L46)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I would set a NOTE here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/integrations/integrations-vuejs.adoc, line 91 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KW2YvKtIfZng4tlM_wd:-KW2YvKtIfZng4tlM_we:b-npt0qt) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/7ef7e6be5d7b21194bb1481aac7e915e3802d190/docs/integrations/integrations-vuejs.adoc#L91)):*
> ```AsciiDoc
> +
> [NOTE]
> You can do the element import also in your index.html. Having the import in the component facilities a lazy loading of elements. The import also takes care of not importing already imported elements.
> ```

The sentence is not clear to me, could you elaborate a bit more ? something like this:

Importing elements directly in the component facilities the lazy loading of web components, and they are imported only when  they are actually used.  
Otherwise, you might  import the element in your `index.html`. This way could fix some issues when using elements properties in the meanwhile it is being downloaded and registered.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79)*

**Comment by samiheikki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/integrations/integrations-vuejs.adoc, line 91 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-KW2YvKtIfZng4tlM_wd:-KW2rVP4Dif7h9UeUBOT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/7ef7e6be5d7b21194bb1481aac7e915e3802d190/docs/integrations/integrations-vuejs.adoc#L91)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> The sentence is not clear to me, could you elaborate a bit more ? something like this:
> 
> Importing elements directly in the component facilities the lazy loading of web components, and they are imported only when  they are actually used.  
> Otherwise, you might  import the element in your `index.html`. This way could fix some issues when using elements properties in the meanwhile it is being downloaded and registered.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/79#-:-KW33GcZbBaUSXkGQoMA:bnfp4nl)*

**Pull request merged**
