### PR TITLE
Improve cdn deployment of master versions

### PR DESCRIPTION
**Pull request by tehapo**
Connects to vaadin/components-team-tasks#194

This PR will introduce generation of a separate `target/bower/bower.json` file with listed `config.masterElements` being deployed from their `master` branches.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core-elements/67)

### CODE REVIEW

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67#-:-KQLHxKp1mU-FzcYxhR5:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[tasks/cdn.js, line 17 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67#-KQLOFztKnLa0Bj-nczq:-KQLOFztKnLa0Bj-nczr:b-q1n9v) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/60eb1f13e5f16538d6d65e0119ab7cded71ad4fa/tasks/cdn.js#L17)):*
> ```JavaScript
> var permalink = config.permalink;
> var stagingPath = path.join(process.cwd(), stagingBasePath, version);
> var testPath = path.join(process.cwd(), stagingPath, 'test');
> ```

`testPath` isn't used anywhere. :man_with_turban: 

---

*[tasks/cdn.js, line 28 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67#-KQLPg1ksbnL_V8j7eiW:-KQLPg1lSOApkuEOPK0d:b-wapszy) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/60eb1f13e5f16538d6d65e0119ab7cded71ad4fa/tasks/cdn.js#L28)):*
> ```JavaScript
> });
> 
> gulp.task('cdn:master:bower', function() {
> ```

Add a dependency to `cdn:stage-bower_components`. Rename to `cdn:stage-bower.json` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67)*

**Comment by tehapo** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[tasks/cdn.js, line 17 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67#-KQLOFztKnLa0Bj-nczq:-KQLUfaL4hmTeO023vtn:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/60eb1f13e5f16538d6d65e0119ab7cded71ad4fa/tasks/cdn.js#L17)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> `testPath` isn't used anywhere. :man_with_turban: 
</details>
Removed.

---

*[tasks/cdn.js, line 28 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67#-KQLPg1ksbnL_V8j7eiW:-KQLUrA0fjzA2bdTjSlo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/60eb1f13e5f16538d6d65e0119ab7cded71ad4fa/tasks/cdn.js#L28)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Add a dependency to `cdn:stage-bower_components`. Rename to `cdn:stage-bower.json` ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67)*

**Comment by Saulis** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 11 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67#-KQPzvSdhxAnWRgyLuT3:-KQPzvSdhxAnWRgyLuT4:bm7v3ni) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/46717c831bbbc19b9b0c29512e17b230c775f48b/gulpfile.js#L11)):*
> ```JavaScript
> });
> 
> gulp.task('clean', ['clean:cdn', 'clean:bower', 'clean:zip']);
> ```

Oh `clean:bower` was removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67)*

**Comment by tehapo** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 11 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67#-KQPzvSdhxAnWRgyLuT3:-KQQ26N7PYKZ0NpgUCVJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-core-elements/blob/46717c831bbbc19b9b0c29512e17b230c775f48b/gulpfile.js#L11)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Oh `clean:bower` was removed?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core-elements/67#-:-KQQ6gIoLHnlLgD478Dx:bnfp4nl)*

**Pull request merged**
